### ISSUE TITLE
depends on maasclient

### ISSUE THREAD

**Issue by mikemccracken** [Ubuntu-Solutions-Engineering/bundle-placement#4]
When used as part of the bigdata-install program, we get this failure:

``` python-traceback
Traceback (most recent call last):
  File "/usr/bin/conjure-setup", line 9, in <module>
    load_entry_point('conjure==0.0.1', 'console_scripts', 'conjure-setup')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/conjure/conjurelib/app.py", line 26, in <module>
    from .controllers import (WelcomeController)
  File "/usr/share/conjure/conjurelib/controllers/__init__.py", line 21, in <module>
    from .welcome import WelcomeController  # noqa
  File "/usr/share/conjure/conjurelib/controllers/welcome.py", line 26, in <module>
    from .provider import ProviderController
  File "/usr/share/conjure/conjurelib/controllers/provider.py", line 22, in <module>
    from .providers import (MaasProviderController,
  File "/usr/share/conjure/conjurelib/controllers/providers/__init__.py", line 21, in <module>
    from .maas import MaasProviderController  # noqa
  File "/usr/share/conjure/conjurelib/controllers/providers/maas.py", line 24, in <module>
    from conjurelib.controllers.deploy import DeployController
  File "/usr/share/conjure/conjurelib/controllers/deploy.py", line 30, in <module>
    from bundleplacer.fixtures.maas import FakeMaasState
  File "/usr/lib/python3/dist-packages/bundleplacer/fixtures/maas.py", line 20, in <module>
    from bundleplacer.maas import MaasMachine
  File "/usr/lib/python3/dist-packages/bundleplacer/maas.py", line 21, in <module>
    from maasclient.auth import MaasAuth
ImportError: No module named 'maasclient'
```

**Comment by mikemccracken** [comment]
fixed by #5
